name: Deploy to AWS EC2 Apache Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Apache Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            #!/bin/bash
            set -e

            # 変数の設定
            REPO_DIR="$HOME/QuickTutor"
            WEB_ROOT="/var/www/html/backend"

            # リポジトリを更新
            echo "Pulling latest code from GitHub repository..."
            cd $REPO_DIR
            git pull origin main

            # 更新されたファイルをコピー
            echo "Copying updated files to web root..."
            sudo rsync -av --delete $REPO_DIR/backend/ $WEB_ROOT/

            # 必要な依存関係をインストール
            echo "Installing PHP dependencies..."
            cd $WEB_ROOT
            sudo /usr/local/bin/composer install --no-dev

            # .envファイルを設定
            echo "Setting environment variables in .env file..."
            cat <<EOL | sudo tee $WEB_ROOT/.env
            APP_NAME=Laravel
            APP_ENV=production
            APP_KEY=${{ secrets.APP_KEY }}
            APP_DEBUG=true
            APP_TIMEZONE=Asia/Tokyo
            APP_URL=https://api.quicktutor.work
            APP_PORT=80

            APP_LOCALE=ja
            APP_FALLBACK_LOCALE=ja
            APP_FAKER_LOCALE=en_US

            APP_MAINTENANCE_DRIVER=file
            APP_MAINTENANCE_STORE=database

            BCRYPT_ROUNDS=12

            LOG_CHANNEL=stack
            LOG_STACK=single
            LOG_DEPRECATIONS_CHANNEL=null
            LOG_LEVEL=debug

            DB_CONNECTION=mysql
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=3306
            DB_DATABASE=quicktutor-rdb
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}

            SESSION_DRIVER=cookie
            SESSION_LIFETIME=120
            SESSION_ENCRYPT=false
            SESSION_PATH=/
            SESSION_SECURE_COOKIE=false
            SESSION_DOMAIN=.quicktutor.work
            SANCTUM_STATEFUL_DOMAINS=api.quicktutor.work:80,quicktutor.work:80,www.quicktutor.work:80

            BROADCAST_CONNECTION=log
            FILESYSTEM_DISK=local
            QUEUE_CONNECTION=database

            CACHE_STORE=database
            CACHE_PREFIX=

            MEMCACHED_HOST=127.0.0.1

            REDIS_CLIENT=phpredis
            REDIS_HOST=redis
            REDIS_PASSWORD=null
            REDIS_PORT=6379

            MAIL_MAILER=smtp
            MAIL_HOST=mailpit
            MAIL_PORT=1025
            MAIL_USERNAME=null
            MAIL_PASSWORD=null
            MAIL_ENCRYPTION=null
            MAIL_FROM_ADDRESS="hello@example.com"
            MAIL_FROM_NAME="Laravel"

            MINIO_API_PORT=9000
            MINIO_CONSOLE_PORT=9001
            MINIO_ROOT_USER=minio_root
            MINIO_ROOT_PASSWORD=minio_password
            MINIO_BUCKET_NAME=quick-tutor

            FILESYSTEM_DISK=s3
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION=ap-northeast-1
            AWS_BUCKET=quicktutor-bucket
            AWS_URL=
            AWS_ENDPOINT=
            AWS_USE_PATH_STYLE_ENDPOINT=true

            VITE_APP_NAME="Laravel"

            SCOUT_DRIVER=meilisearch
            MEILISEARCH_HOST=http://meilisearch:7700

            MEILISEARCH_NO_ANALYTICS=false

            WWWUSER=1000
            WWWGROUP=1000
            EOL

            # Laravelのキャッシュをクリア
            echo "Clearing Laravel cache..."
            sudo php $WEB_ROOT/artisan optimize:clear

            # データベースのマイグレーションとシーディング
            echo "Running database migrations and seeders..."
            sudo php $WEB_ROOT/artisan migrate --force
            sudo php $WEB_ROOT/artisan db:seed --force

            # コンフィグ、ルート、ビューのキャッシュを作成
            echo "Caching configuration..."
            sudo php $WEB_ROOT/artisan config:clear

            echo "Caching routes..."
            sudo php $WEB_ROOT/artisan route:cache

            # ビューキャッシュの作成（失敗を許容）
            echo "Caching views..."
            sudo php $WEB_ROOT/artisan view:cache || true

            # シンボリックリンクを作成
            echo "Creating storage symlink..."
            if [ -L "$WEB_ROOT/public/storage" ]; then
              echo "Removing existing storage symlink..."
              sudo rm $WEB_ROOT/public/storage
            fi
            sudo php $WEB_ROOT/artisan storage:link

            # ディレクトリの権限を設定
            echo "Setting directory permissions..."
            sudo chown -R apache:apache $WEB_ROOT
            sudo chmod -R 755 $WEB_ROOT
            sudo chmod -R 775 $WEB_ROOT/storage
            sudo chmod -R 775 $WEB_ROOT/bootstrap/cache

            # ログファイルの権限を設定
            echo "Setting log file permissions..."
            sudo chown -R apache:apache $WEB_ROOT/storage/logs
            sudo chmod -R 775 $WEB_ROOT/storage/logs

            # Apacheを再起動
            echo "Restarting Apache server..."
            sudo systemctl restart httpd

            echo "Deployment script completed successfully."
          EOF
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
